title: JackShen Portfolio

author: JackShen

description: Portfolio with my best projects

logo: https://raw.githubusercontent.com/Russkiy-Voyennyy-Korabl-Idi-Nakhuy/Russkiy-Voyennyy-Korabl-Idi-Nakhuy.github.io/master/img/intro.webp

google_analytics: G-6YW2L42J25

url: https://russkiy-voyennyy-korabl-idi-nakhuy.github.io

base_url: ""

permalink: /

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md